# Generated by Django 4.1.3 on 2023-03-26 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USMAApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(default='@gmail.com', max_length=100)),
                ('Phone', models.CharField(default='+255', max_length=13)),
                ('TeacherImage', models.ImageField(blank=True, null=True, upload_to='media/StudentImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('course', models.ManyToManyField(max_length=200, to='USMAApp.universitycourses')),
                ('university', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(default='@gmail.com', max_length=100)),
                ('Phone', models.CharField(default='+255', max_length=13)),
                ('StudentImage', models.ImageField(blank=True, null=True, upload_to='media/StudentImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universitycourses')),
                ('university', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModuleName', models.CharField(blank=True, max_length=100, null=True)),
                ('ModuleImage', models.ImageField(blank=True, null=True, upload_to='media/ModuleImage/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universitycourses')),
                ('university', models.ManyToManyField(max_length=200, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'Modules',
            },
        ),
    ]
