# Generated by Django 4.1.3 on 2023-04-06 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USMAApp', '0003_modules_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=500)),
                ('StudentName', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=50)),
                ('ProjectBody', models.TextField(blank=True, max_length=10000, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('ProjectImage', models.ImageField(blank=True, null=True, upload_to='media/UniversityImage/')),
                ('PdfFile', models.CharField(blank=True, max_length=100, null=True)),
                ('VideoLink', models.CharField(blank=True, max_length=200, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('CourseName', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universitycourses')),
                ('university', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'AllProjects',
            },
        ),
    ]
