# Generated by Django 4.1.3 on 2023-04-22 09:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USMAApp', '0006_alter_allprojects_pdffile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticlesName', models.CharField(max_length=1000)),
                ('ArticleImage', models.ImageField(blank=True, null=True, upload_to='media/ArticlesImage/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='ArticlesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WrittenBy', models.CharField(blank=True, default='Dimoso Junior', max_length=100, null=True)),
                ('ArticleBody', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('ShortDescription', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('ArticleImage', models.ImageField(blank=True, null=True, upload_to='media/ArticlesImage/')),
                ('Github', models.CharField(blank=True, default='www.github.com', max_length=1000, null=True)),
                ('Youtube', models.CharField(blank=True, default='www.youtube.com', max_length=1000, null=True)),
                ('year', models.CharField(blank=True, default='2023', max_length=100, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('ArticlesName', models.ForeignKey(max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.articles')),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
