# Generated by Django 4.1.3 on 2023-04-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USMAApp', '0008_allprojects_pdf_articlescategory_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescategory',
            options={'verbose_name_plural': 'ArticlesCategory'},
        ),
        migrations.AlterField(
            model_name='articlescategory',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/ArticlesPDF/'),
        ),
    ]
